name: Deploy to Heroku

on:
  push:
    branches:
      - main  # or your desired deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install Node.js environment
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # Install project dependencies
      - name: Install dependencies
        run: npm install

      # Build the project (if applicable)
      - name: Build
        run: npm run build --if-present

      # Install Heroku CLI
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      # Deploy to Heroku
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "your-heroku-app-name" # replace with your actual Heroku app name
          heroku_email: "your-email@example.com" # replace with your actual Heroku email
